/// One row per day from 1 January 2015 to 31 January 2018, contiguous, and marked as
/// the date table.
///
/// 'Series' marks the day the extract changes generator, early in October 2017. From
/// then on every order has one line, orders arrive at an almost fixed rate, and most of
/// the catalogue is replaced. The trend visuals stop before it; nothing else hides it.
table Date
	lineageTag: 81a733e1-7b48-5e51-be62-5931c7443408
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: d mmm yyyy
		lineageTag: 2c80ddb6-88bc-5ae6-905d-afc05ac850a9
		summarizeBy: none
		sourceColumn: Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 4ee373bf-d00e-5b6b-a332-5fc8a9f35b18
		summarizeBy: none
		sourceColumn: Year

	column Quarter
		dataType: string
		lineageTag: 4ab71a52-a71d-55a9-babc-1102d6dd5441
		summarizeBy: none
		sourceColumn: Quarter

	column 'Month No'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a0d22b99-7c48-5134-b6e7-323d9c71bff6
		summarizeBy: none
		sourceColumn: MonthNumber

	column Month
		dataType: string
		lineageTag: 184b2de2-bf24-5a06-ae67-8bbef9ddeba6
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: 'Month No'

	column 'Month Short'
		dataType: string
		lineageTag: a4a175e1-be5f-58cd-bb90-e9b3147945f2
		summarizeBy: none
		sourceColumn: MonthShort
		sortByColumn: 'Month No'

	column 'Month Year'
		dataType: string
		lineageTag: 594c0ae6-31b5-570c-8774-093b566d4ec8
		summarizeBy: none
		sourceColumn: MonthYear
		sortByColumn: 'Month Year Sort'

	column 'Month Year Sort'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7285d22b-7d60-5039-8806-be422daa1917
		summarizeBy: none
		sourceColumn: MonthYearSort

	column 'Month Start'
		dataType: dateTime
		formatString: mmm yyyy
		lineageTag: 976c7f0a-e851-5b3c-b3b5-84153851f1c8
		summarizeBy: none
		sourceColumn: MonthStart

	column Series
		dataType: string
		lineageTag: 5af93faf-969f-5d78-93ac-912a0ae27671
		summarizeBy: none
		sourceColumn: Series

	/// Yes for January to September - the months every year's main series has.
	column 'In Jan To Sep'
		dataType: string
		lineageTag: 812d4679-ecf1-5b35-a043-ae6c55017cae
		summarizeBy: none
		sourceColumn: InJanToSep

	partition Date = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/owilliams84/powerbi-supply-chain/main/data/dim_date.csv"), [Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Applied Types" = Table.TransformColumnTypes(#"Promoted Headers", {{"Date", type date}, {"Year", Int64.Type}, {"Quarter", type text}, {"MonthNumber", Int64.Type}, {"MonthName", type text}, {"MonthShort", type text}, {"MonthYear", type text}, {"MonthYearSort", Int64.Type}, {"MonthStart", type date}, {"Series", type text}, {"InJanToSep", type text}})
				in
				    #"Applied Types"

	annotation PBI_ResultType = Table
