/// One row per day from 1 January 2015 to 31 January 2018, contiguous, and marked as
/// the date table.
///
/// 'Series' marks the day the extract changes generator, early in October 2017. From
/// then on every order has one line, orders arrive at an almost fixed rate, and most of
/// the catalogue is replaced. The trend visuals stop before it; nothing else hides it.
table Date
	lineageTag: 81a733e1-7b48-5e51-be62-5931c7443408
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: d mmm yyyy
		lineageTag: 2c80ddb6-88bc-5ae6-905d-afc05ac850a9
		summarizeBy: none
		sourceColumn: Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 4ee373bf-d00e-5b6b-a332-5fc8a9f35b18
		summarizeBy: none
		sourceColumn: Year

	column Quarter
		dataType: string
		lineageTag: 4ab71a52-a71d-55a9-babc-1102d6dd5441
		summarizeBy: none
		sourceColumn: Quarter

	column 'Month No'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a0d22b99-7c48-5134-b6e7-323d9c71bff6
		summarizeBy: none
		sourceColumn: MonthNumber

	column Month
		dataType: string
		lineageTag: 184b2de2-bf24-5a06-ae67-8bbef9ddeba6
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: 'Month No'

	column 'Month Short'
		dataType: string
		lineageTag: a4a175e1-be5f-58cd-bb90-e9b3147945f2
		summarizeBy: none
		sourceColumn: MonthShort
		sortByColumn: 'Month No'

	column 'Month Year'
		dataType: string
		lineageTag: 594c0ae6-31b5-570c-8774-093b566d4ec8
		summarizeBy: none
		sourceColumn: MonthYear
		sortByColumn: 'Month Year Sort'

	column 'Month Year Sort'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7285d22b-7d60-5039-8806-be422daa1917
		summarizeBy: none
		sourceColumn: MonthYearSort

	column 'Month Start'
		dataType: dateTime
		formatString: mmm yyyy
		lineageTag: 976c7f0a-e851-5b3c-b3b5-84153851f1c8
		summarizeBy: none
		sourceColumn: MonthStart

	column Series
		dataType: string
		lineageTag: 5af93faf-969f-5d78-93ac-912a0ae27671
		summarizeBy: none
		sourceColumn: Series

	/// Yes for January to September - the months every year's main series has.
	column 'In Jan To Sep'
		dataType: string
		lineageTag: 812d4679-ecf1-5b35-a043-ae6c55017cae
		summarizeBy: none
		sourceColumn: InJanToSep

	column 'Cal Year' = YEAR('Date'[Date])
		dataType: int64
		formatString: 0
		displayFolder: Calendar
		lineageTag: 0707735f-8b33-5c12-8519-ea061eb4fefd
		summarizeBy: none

	column 'Cal Month No' = MONTH('Date'[Date])
		dataType: int64
		formatString: 0
		displayFolder: Calendar
		lineageTag: aefb08f8-9a31-5984-a769-6d1c6b81b53e
		summarizeBy: none

	/// Month name, January to December.
	column 'Cal Month' = FORMAT('Date'[Date], "mmmm")
		dataType: string
		displayFolder: Calendar
		lineageTag: f517e666-5b8b-54f8-ad4b-f1565198e606
		summarizeBy: none
		sortByColumn: 'Cal Month No'

	column 'Cal Month Short' = FORMAT('Date'[Date], "mmm")
		dataType: string
		displayFolder: Calendar
		lineageTag: 0007557c-f0a4-50ec-823d-d01c28c9697a
		summarizeBy: none
		sortByColumn: 'Cal Month No'

	column 'Cal Quarter' = "Q" & ROUNDUP(MONTH('Date'[Date]) / 3, 0)
		dataType: string
		displayFolder: Calendar
		lineageTag: cc9039da-83a6-5ad1-9bd0-dadb381aba8d
		summarizeBy: none

	column 'Cal Quarter Key' = YEAR('Date'[Date]) * 10 + ROUNDUP(MONTH('Date'[Date]) / 3, 0)
		dataType: int64
		formatString: 0
		displayFolder: Calendar
		lineageTag: 3506becd-5052-54f0-9797-5bf34820d15a
		summarizeBy: none

	column 'Cal Quarter Label' = "Q" & ROUNDUP(MONTH('Date'[Date]) / 3, 0) & " " & YEAR('Date'[Date])
		dataType: string
		displayFolder: Calendar
		lineageTag: bf3802ed-2258-5175-a230-389443c61d08
		summarizeBy: none
		sortByColumn: 'Cal Quarter Key'

	column 'Cal Month in Quarter No' = MOD(MONTH('Date'[Date]) - 1, 3) + 1
		dataType: int64
		formatString: 0
		displayFolder: Calendar
		lineageTag: 85cff6d8-680c-5b29-9444-fe7baacc501c
		summarizeBy: none

	/// The Month view's column headers.
	column 'Cal Month in Quarter' = SWITCH(MOD(MONTH('Date'[Date]) - 1, 3) + 1, 1, "1st month", 2, "2nd month", "3rd month")
		dataType: string
		displayFolder: Calendar
		lineageTag: 1847c52e-e9ce-5b90-9243-b7ebd37b28c1
		summarizeBy: none
		sortByColumn: 'Cal Month in Quarter No'

	/// Monday = 1.
	column 'Cal Weekday No' = WEEKDAY('Date'[Date], 2)
		dataType: int64
		formatString: 0
		displayFolder: Calendar
		lineageTag: 0e9a5c4d-ab83-5ac2-9aad-fc60625803ae
		summarizeBy: none

	/// Mon to Sun, in that order - the Day view's column headers.
	column 'Cal Day Short' = FORMAT('Date'[Date], "ddd")
		dataType: string
		displayFolder: Calendar
		lineageTag: 0b33e196-2324-5c24-89f1-442a02ca8ff0
		summarizeBy: none
		sortByColumn: 'Cal Weekday No'

	column 'Cal Day Name' = FORMAT('Date'[Date], "dddd")
		dataType: string
		displayFolder: Calendar
		lineageTag: 4e3be1cc-3be7-5e32-a71d-5bf299a50deb
		summarizeBy: none
		sortByColumn: 'Cal Weekday No'

	/// Which row of a Monday-first month grid the day sits on: 1 to 6.
	column 'Cal Week of Month' = INT((DAY('Date'[Date]) + WEEKDAY(DATE(YEAR('Date'[Date]), MONTH('Date'[Date]), 1), 2) - 2) / 7) + 1
		dataType: int64
		formatString: 0
		displayFolder: Calendar
		lineageTag: 9da8ec8d-55ef-590d-8b04-b67ce206e7e0
		summarizeBy: none

	column 'Cal Week Row' = REPT(UNICHAR(8203), INT((DAY('Date'[Date]) + WEEKDAY(DATE(YEAR('Date'[Date]), MONTH('Date'[Date]), 1), 2) - 2) / 7) + 1)
		dataType: string
		displayFolder: Calendar
		lineageTag: c334bf3b-7322-5e1d-bf3e-8826851aad04
		summarizeBy: none
		sortByColumn: 'Cal Week of Month'

	partition Date = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/owilliams84/powerbi-supply-chain/main/data/dim_date.csv"), [Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Applied Types" = Table.TransformColumnTypes(#"Promoted Headers", {{"Date", type date}, {"Year", Int64.Type}, {"Quarter", type text}, {"MonthNumber", Int64.Type}, {"MonthName", type text}, {"MonthShort", type text}, {"MonthYear", type text}, {"MonthYearSort", Int64.Type}, {"MonthStart", type date}, {"Series", type text}, {"InJanToSep", type text}})
				in
				    #"Applied Types"

	annotation PBI_ResultType = Table
