/// What happened to the order: how it was paid, its order status and its delivery
/// status, one row per combination that occurs.
///
/// Payment type decides order status outright: cash is always Closed, debit always
/// Complete or On hold, and every suspected fraud is a bank transfer. Useful to know
/// before reading a fraud pattern into it.
table Outcome
	lineageTag: 232f388f-ca46-5620-91ea-a0d8457d0117

	column 'Outcome Key'
		dataType: int64
		isHidden
		isKey
		formatString: 0
		lineageTag: ae928e35-3cd9-5144-a4f5-98476f9c6201
		summarizeBy: none
		sourceColumn: OutcomeKey

	column 'Payment Type'
		dataType: string
		lineageTag: d14d95d6-11a5-58d9-b8b7-285668c1cf50
		summarizeBy: none
		sourceColumn: PaymentType

	column 'Order Status'
		dataType: string
		lineageTag: c5a1353c-05d2-5977-9b16-dc92a864243d
		summarizeBy: none
		sourceColumn: OrderStatus

	column 'Delivery Status'
		dataType: string
		lineageTag: 7f5ad65f-9818-52f7-b5f7-5f47bfbe105b
		summarizeBy: none
		sourceColumn: DeliveryStatus
		sortByColumn: 'Delivery Sort'

	column 'Delivery Sort'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 23649e62-174f-5344-9257-149e9f28ef28
		summarizeBy: none
		sourceColumn: DeliverySort

	/// Yes for cancelled and suspected-fraud orders: they did not ship.
	column 'Is Cancelled'
		dataType: string
		lineageTag: 7db1ae7d-bb41-5c85-a538-3b1e73d0e7cf
		summarizeBy: none
		sourceColumn: IsCancelled

	column 'Is Suspected Fraud'
		dataType: string
		lineageTag: e1fdb635-5b3d-55b3-babf-9d7118257680
		summarizeBy: none
		sourceColumn: IsSuspectedFraud

	partition Outcome = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/owilliams84/powerbi-supply-chain/main/data/dim_outcome.csv"), [Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Applied Types" = Table.TransformColumnTypes(#"Promoted Headers", {{"OutcomeKey", Int64.Type}, {"PaymentType", type text}, {"OrderStatus", type text}, {"DeliveryStatus", type text}, {"DeliverySort", Int64.Type}, {"IsCancelled", type text}, {"IsSuspectedFraud", type text}})
				in
				    #"Applied Types"

	annotation PBI_ResultType = Table
