/// The four shipping modes and the lead time each one promises.
table 'Shipping Mode'
	lineageTag: 6e0cb1a8-b19a-582a-ade6-7ff8e93994fb

	column 'Mode Key'
		dataType: int64
		isHidden
		isKey
		formatString: 0
		lineageTag: e5127f3f-2f35-5dd4-9c95-c400226e859d
		summarizeBy: none
		sourceColumn: ModeKey

	column 'Shipping Mode'
		dataType: string
		lineageTag: 73a5c978-ddfe-503a-a2a4-d0377f282b35
		summarizeBy: none
		sourceColumn: ShippingMode
		sortByColumn: 'Mode Key'

	column 'Promised Days'
		dataType: int64
		formatString: 0
		lineageTag: b0e44454-1fd8-569d-824b-ae25346a3d82
		summarizeBy: none
		sourceColumn: PromisedDays

	partition 'Shipping Mode' = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/owilliams84/powerbi-supply-chain/main/data/dim_shipping_mode.csv"), [Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Applied Types" = Table.TransformColumnTypes(#"Promoted Headers", {{"ModeKey", Int64.Type}, {"ShippingMode", type text}, {"PromisedDays", Int64.Type}})
				in
				    #"Applied Types"

	annotation PBI_ResultType = Table
